- name: Setup Jenkins
  hosts: Bastion_Host
  become: yes
  vars:
    java_packages: java-17-amazon-corretto-devel
    jenkins_packages: jenkins
  tasks:
    - name: Download Jenkins repository file
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins-CI key
      command: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Install Java
      yum:
        name: "{{ java_packages }}"
        state: present

    - name: Install Jenkins
      yum:
        name: "{{ jenkins_packages }}"
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started

    - name: Set Jenkins user shell to Bash
      user:
        name: jenkins
        shell: /bin/bash
       
