- name: Install kubectl&GIT
  hosts: Bastion_Host
  become: yes 
  vars:
    home_dir: /home/zeinab
    jenkins_home: /var/lib/jenkins  
  tasks:
    - name: Download kubectl binary
      command: curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.31.0/2024-09-12/bin/linux/amd64/kubectl

    - name: Copy kubectl to /usr/local/bin
      command: sudo cp ./kubectl /usr/local/bin/

    - name: make kubectl executable
      become: yes
      file:
        path: /usr/local/bin/kubectl
        mode: '0755'


    - name: Create .aws directory for jenkins user
      file:
        path: "{{ jenkins_home }}/.aws"
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0700'

    - name: Copy AWS credentials to jenkins user home directory
      copy:
        src: "{{ home_dir }}/.aws/credentials"
        dest: "{{ jenkins_home }}/.aws/credentials"
        owner: jenkins
        group: jenkins        

    - name: Configure kubectl for Jenkins using AWS CLI
      become_user: jenkins  # Switch to jenkins user
      command: "aws eks --region us-east-1 update-kubeconfig --name eksdemo"

    - name: Install GIT 
      dnf:
        name: git
        state: present        
